### ISSUE TITLE
Connect Wallet

### ISSUE THREAD

**Issue by Seyaji** [Seyaji/marketplace#1]
Complete the connect wallet integration for the site

**Comment by metanodes** [comment]
Working on this. I'll try to commit the code today

**Comment by Seyaji** [comment]
Awesome!
Looking forward to seeing it :)

**Comment by metanodes** [comment]
@Seyaji Can you provide access to this git id ? Getting the following error :
````
> git push origin walletconnect
remote: Permission to Seyaji/marketplace.git denied to metanodes.
fatal: unable to access 'https://github.com/Seyaji/marketplace/': The requested URL returned error: 403
````

**Comment by Seyaji** [comment]
@metanodes  I added you as a collaborator, you should have received an email or some kind of link, once you accept you can push
